@startuml
title PatientDomainServiceApplication

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary("PatientDomainServiceApplication.PatientDomainServiceApplication_boundary", "PatientDomainServiceApplication", $tags="") {
  Component(PatientDomainServiceApplication.PatientDomainServiceApplication.Metadata, "Metadata", "Module", "", $tags="")
  Component(PatientDomainServiceApplication.PatientDomainServiceApplication.Arrival, "Arrival", "Module", "", $tags="")
}

Rel_D(PatientDomainServiceApplication.PatientDomainServiceApplication.Arrival, PatientDomainServiceApplication.PatientDomainServiceApplication.Metadata, "uses", $tags="")

SHOW_LEGEND(true)
@enduml